all:
    # install pycocotools locally
	python3.6 setup.py build_ext --inplace
#	/usa/yliu1/anaconda3/envs/fiber/bin/python setup.py build_ext --inplace
	rm -rf build

install:
	# install pycocotools to the Python site-packages
	python setup.py build_ext install
  	#/usa/yliu1/anaconda3/envs/fiber/bin/python setup.py build_ext install 
	rm -rf build
