RADIUS:
  INPUT: '/opt/FTE/users/chrgao/datasets/Textile/data_annotation/txt_format/cls_reg/2019_for_test_filter.txt'
  OUTPUT: '/opt/fte/users/chrgao/code/torch_fruit/output/default/train_fiber_dataset_classify/run2/test_ouput/2019_for_test_filter_radius.txt'
  STEP: 1
  MAX_ITER: 255
  SHOW_POINTS: False
  SAMPLER_NUM: 500